server:
  port: 80

spring:
  cloud:
    gateway:
      routes:
        - id: baidu
          uri: https://www.baidu.com
          predicates:
            - Path=/baidu/**
          filters:
            # https://www.baidu.com/baidu/** -> https://www.baidu.com/**
            - StripPrefix=1

        # 百度搜索
        - id: baidu_s
          uri: https://www.baidu.com
          predicates:
            - Path=/s
