eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 2223

mybatis:
  config-location: classpath:META-INF/mybatis-config.xml

spring:
  application:
    name: hubu-service-bill

  redis:
    redisson:
      file: classpath:redisson.yaml

  shardingsphere:
    datasource:
      names: hubu
      hubu:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/hubu?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: xianzhan
        password: xianzhan
    rules:
      sharding:
        tables:
          hb_car_bill:
            actual-data-nodes: hb_car_bill_$->{0..1}
            table-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: hb-car-bill-inline
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
        sharding-algorithms:
          hb-car-bill-inline:
            type: INLINE
            props:
              algorithm-expression: hb_car_bill_$->{id % 2}
        key-generators:
          snowflake:
            type: SNOWFLAKE
